// Libraries:
#include <Arduino.h> // main library header for arduino boards
#include "DCMDriverL298.h" // dual H-bridge motor driver
#include "NewPing.h"
#include "Wire.h"
#include <stdio.h>

// Pin definitions
// Just blantantly copied from auto-generated code in /Firmware
#define DCMOTORDRIVERL298_PIN_INT1	2
#define DCMOTORDRIVERL298_PIN_ENB	6
#define DCMOTORDRIVERL298_PIN_INT2	3
#define DCMOTORDRIVERL298_PIN_ENA	5
#define DCMOTORDRIVERL298_PIN_INT3	4
#define DCMOTORDRIVERL298_PIN_INT4	7
#define HCSR04_1_PIN_TRIG	9
#define HCSR04_1_PIN_ECHO	8
#define HCSR04_2_PIN_TRIG	11
#define HCSR04_2_PIN_ECHO	10

// Global vars and defs
int ECHO_DUR_1 = 9;
int ECHO_DIST_1 = 8;
int ECHO_DUR_2 = 11;
int ECHO_DIST_2 = 10;

// Object init

/*
  DevNotes. NewPing objects (generated by circuito.io) takes in 2 parameters: trigger pin and echo pin; then output according to called attributes.
  - For example: get the distance from the sensor: `sensorname.ping_cm()`;
*/

NewPing hcsr04_1(HCSR04_1_PIN_TRIG, HCSR04_1_PIN_ECHO);
NewPing hcsr04_2(HCSR04_2_PIN_TRIG, HCSR04_2_PIN_ECHO);


/*
  DevNotes:
  - Creating new objects with existing class attributes in imported libraries.
  - Mostly DC motor driver var inits.
*/

DCMDriverL298 dcMotorDriverL298(DCMOTORDRIVERL298_PIN_ENA, DCMOTORDRIVERL298_PIN_INT1, DCMOTORDRIVERL298_PIN_INT2, DCMOTORDRIVERL298_PIN_ENB, DCMOTORDRIVERL298_PIN_INT3, DCMOTORDRIVERL298_PIN_INT4);

//println("Debug message: All objects and variables initialized.");
//println("All libraries and headers imported succulently.");

// Setup
void setup() {

  // Debugging
  Serial.begin(9600);
  while (!Serial);

  Serial.println("now starting drive program...");
  delay(100);
}

void loop() {
  // Designated: MotorA - right, MotorB - left
  // Designated: hcsr04_1 - sensor front, hcsr04_2 - sensor left
  if (hcsr04_1.ping_cm() >= 25) {
    dcMotorDriverL298.setMotorA(200, 1);
    dcMotorDriverL298.setMotorB(200, 1);
  }
  else {
    if (hcsr04_2.ping_cm() <= 10) { // left-mounted sensor, to turn right, left wheel needs to go forward.
      dcMotorDriverL298.setMotorB(200, 1);
      dcMotorDriverL298.setMotorA(10, 0); // this is to add a bit resistance in right wheel so the turn is more sharp
      delay(100); // theoretical time it takes to turn.
    }
    else {
      dcMotorDriverL298.setMotorA(200, 1);
      dcMotorDriverL298.setMotorB(10, 0); // same thing as with turning right
      delay(100);
    };
  };
}
